# Generated by Django 4.0.2 on 2022-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
