# Generated by Django 4.0.2 on 2022-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
